### ISSUE TITLE
not able to install

### ISSUE THREAD

**Issue by ajai06** [convergencelabs/ace-collab-ext#14]
currently am using angular 6 . when i try npm install --save-dev @convergencelabs/ace-collab-ext  

"npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@convergencelabs%2face-collab-ext - Not found
npm ERR! 404 
npm ERR! 404  '@convergencelabs/ace-collab-ext@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
"
please check

**Comment by mmacfadden** [comment]
Thanks for reporting. This is a bug in the documentation on GitHub. We are in the process of moving the project to a new namespace. The current published version is at:

`npm install --save-dev @convergence/ace-collab-ext`

**Comment by ajai06** [comment]
thanks. in this package there is an error in d.ts file.
file: typings/AceRadarView.d.ts
-> import { Ace } from "Ace-builds"; (used Ace instead of ace);
all other files contains import { Ace } from "ace-builds";

**Comment by mmacfadden** [comment]
Is the version you pulled in 0.3.0?  I believe this commit fixed that issue:

https://github.com/convergencelabs/ace-collab-ext/commit/ca63484c96ed78a713cdfbc4357fbb9dd377fac8

**Comment by ajai06** [comment]
"@convergence/ace-collab-ext": "^0.4.0"
which i installed

**Comment by mmacfadden** [comment]
Ok. Look like we need to make a quick release to correct that then. I will do that right now.

**Comment by ajai06** [comment]
thanks alot :)

**Comment by mmacfadden** [comment]
Pushed an update here:

https://www.npmjs.com/package/@convergencelabs/ace-collab-ext

Notice the scope has now changed.
