### ISSUE TITLE
Bad import on AceRadarView

### ISSUE THREAD

**Issue by mmacfadden** [convergencelabs/ace-collab-ext#15]
@ajai06 Reported that there was an errant import on in the AceRadarView class in the 0.4.0 release.

**Comment by mmacfadden** [comment]
Fixed in version 0.5.0.  Note that the scope has change.  New location is now:

https://www.npmjs.com/package/@convergencelabs/ace-collab-ext

**Comment by ajai06** [comment]
Thank you so much !😊

**Comment by mmacfadden** [comment]
Thanks for reporting! Let us know if that does not solve the issue.
