### ISSUE TITLE
Marker Layer not working for ace custom cursor

### ISSUE THREAD

**Issue by yadurvt** [convergencelabs/ace-collab-ext#16]
markerLayer.elt is not a function.
When this function is executed ,curMgr.addCursor("uid1", "User 1", "orange", {row: 0, column: 10});

**Comment by mmacfadden** [comment]
Was there a resolution to this, or did you figure something out?  I might be able to add a better error message.

**Comment by LucasGobbs** [comment]
Getting the same error, did you find the reason or any workaround? @yadurvt
