### ISSUE TITLE
Remote cursor position stuck at {0, 0}

### ISSUE THREAD

**Issue by rafeautie** [convergencelabs/ace-collab-ext#9]
The index is being transmitted to connected clients. The setup I have now is basically identical to the example. If you look at the "set" listener, both `reference.sessionId()` and `reference.value()` are correct. I followed the code and the index (reference.value()) gets converted to the `{row,col}` formatted properly. This makes it all the way to the `addDynamicCursor`. So I have no idea where it goes wrong.

I would like to add that I am using [react-ace](https://github.com/securingsincity/react-ace).

```javascript
const cursorKey = "cursor";
let cursorReference = null;
let cursorManager = null;

const initSharedCursors = (textModel) => {
  cursorManager = new AceCollabExt.AceMultiCursorManager(editor.getSession());
  cursorReference = textModel.indexReference(cursorKey);

  const references = textModel.references({ key: cursorKey });
  references.forEach((ref) => {
    if (!ref.isLocal()) addCursor(ref);
  })

  setLocalCursor();
  cursorReference.share();
  
  editor.getSession().selection.on('changeCursor', () => setLocalCursor());
  
  textModel.on('reference', (e) => {
    if (e.reference.key() === cursorKey) addCursor(e.reference);
  });
}

const setLocalCursor = () => {
  const position = editor.getCursorPosition();
  const index = doc.positionToIndex(position);
  cursorReference.set(index);
}

const addCursor = (reference) => {
  const color = colorAssigner.getColorAsHex(reference.sessionId());
  const remoteCursorIndex = reference.value();
  
  cursorManager.addCursor(reference.sessionId(), reference.user().displayName, color, remoteCursorIndex);
  
  reference.on("cleared", () => cursorManager.clearCursor(reference.sessionId()));
  reference.on("disposed", () => cursorManager.removeCursor(reference.sessionId()));
  reference.on("set", () => {
    cursorManager.setCursor(reference.sessionId(), reference.value())
  });
}
```

**Comment by mmacfadden** [comment]
So the remote cursor does show up... its just not moving around?

Do you know what version of ACE is being pulled in by React Ace?

**Comment by rafeautie** [comment]
@mmacfadden  Yea... version 1.4.6

**Comment by alalonde** [comment]
Bit of a guess here, but it could be that since `react-ace` is rendering the underlying ace editor, it's conflicting with our extension's manipulation of ace directly.  If you could extract the relevant code into a [plunk](https://plnkr.co/) or something we can do some proper debugging.

**Comment by mmacfadden** [comment]
@alalonde I had this thought too.. but.... the dynamic cursor is showing up. And react-ace wouldn't even know it was there theoretically. I could see this being the case if it was preventing the dynamic cursor from showing up at all.  But since it shows up, I am pretty sure the react-ace wouldn't know how to go in and influence our rendering.

I am partly wondering if there is some css issue somewhere which is preventing our css attributes from properly moving the cursor.

**Comment by rafeautie** [comment]
I might try and use ace without the react-ace wrapper and see if it changes anything.

**Comment by JeSuisUnCaillou** [comment]
> I am partly wondering if there is some css issue somewhere which is preventing our css attributes from properly moving the cursor

I had the same issue with the cursor stuck at [0;0], and I inspected the css to see if I could find the issue. Turns out I just needed a bit of css to solve the problem :

```css
.ace-multi-cursor, .ace-multi-cursor-tooltip {
  position: absolute;
}
```

I hope it can still help you :)

**Comment by mmacfadden** [comment]
@JeSuisUnCaillou quick question.  The css file included in the build: https://github.com/convergencelabs/ace-collab-ext/blob/3399b7caccfbe981e53446711bb8b1e1691a540e/src/css/ace-collab-ext.css#L1 

Should already contain these. Were you including the css file?

**Comment by JeSuisUnCaillou** [comment]
> Were you including the css file?

I wasn't ! :man_facepalming: 

I imported it in my scss from my `node_modules`, and it worked like a charm :+1: 

```
@import './path/to/node_modules/@convergence/ace-collab-ext/css/ace-collab-ext.min.css';
``` 

As it wasn't specified in the Readme file, I assumed I was good to go with just `npm install --save-dev @convergencelabs/ace-collab-ext`.

I recommend mentionning somewhere in the install documentation that you need to include the css file in your page, so future users don't miss it.
